// src/common/AdvancedAddDownloadForm.tsx
import * as React from 'react';
import { last } from 'lodash-es';
import { ApiClient } from 'synology-typescript-api';
import * as classNamesProxy from 'classnames';

// https://github.com/rollup/rollup/issues/1267
const classNames: typeof classNamesProxy = (classNamesProxy as any).default || classNamesProxy;

import { PathSelector } from './PathSelector';

export interface Props {
  client: ApiClient;
  onAddDownload: (url: string, path: string | undefined) => void;
  onCancel: () => void;
}

export interface State {
  selectedPath: string | undefined;
  downloadUrl: string;
}

export class AdvancedAddDownloadForm extends React.PureComponent<Props, State> {
  state: State = {
    selectedPath: undefined,
    downloadUrl: ''
  };

  render() {
    const hasDownloadUrl = this.state.downloadUrl.length > 0;

    return (
      <div className='advanced-add-download-form'>
        <input
          type='text'
          placeholder={browser.i18n.getMessage('URL_to_download')}
          value={this.state.downloadUrl}
          onChange={e => { this.setState({ downloadUrl: e.currentTarget.value }); }}
          className='url-input card'
        />
        <div className='download-path card'>
          <div className='path-display' title={this.state.selectedPath}>
            {browser.i18n.getMessage('Download_to')}
            <span className={classNames('path', { 'faded': !this.state.selectedPath })}>
              {this.state.selectedPath ? last(this.state.selectedPath.split('/')) : browser.i18n.getMessage('default_location')}
            </span>
          </div>
          <PathSelector
            client={this.props.client}
            onSelectPath={this.setSelectedPath}
            selectedPath={this.state.selectedPath}
          />
        </div>
        <div className='buttons'>
          <button
            onClick={this.props.onCancel}
            title={browser.i18n.getMessage('Dont_add_a_new_task')}
          >
            <span className='fa fa-lg fa-times'/> {browser.i18n.getMessage('Cancel')}
          </button>
          <button
            onClick={this.addDownload}
            title={browser.i18n.getMessage('Download_the_above_URL_to_the_specified_location')}
            disabled={!hasDownloadUrl}
            className={classNames({ 'disabled': !hasDownloadUrl })}
          >
            <span className='fa fa-lg fa-plus'/> {browser.i18n.getMessage('Add')}
          </button>
        </div>
      </div>
    );
  }

  private addDownload = () => {
    this.props.onAddDownload(this.state.downloadUrl, this.state.selectedPath);
  };

  private setSelectedPath = (selectedPath: string) => {
    this.setState({ selectedPath });
  };
}

// src/popup/AdvancedAddDownloadForm.svelte
<script lang="ts">
  import Icon from "../common/components/Icon.svelte";
  import PathSelector from "./PathSelector.svelte";
  import { startsWithAnyProtocol, ALL_DOWNLOADABLE_PROTOCOLS } from "../common/apis/protocols";
  import type { PopupClient } from "./popupClient";

  interface Props {
    onClose: () => void;
    client: PopupClient;
  }

  let { onClose, client }: Props = $props();

  let selectedPath = $state<string | undefined>(undefined);
  let downloadUrl = $state("");
  let unzipPassword = $state("");
  let unzipEnabled = $state(true);

  let hasDownloadUrl = $derived(downloadUrl.length > 0);

  async function updateIsUnzipEnabled() {
    try {
      const response = await client.getConfig();
      if (!response.success) {
        unzipEnabled = false;
      } else {
        unzipEnabled = response.result.enable_unzip_service;
      }
    } catch {
      unzipEnabled = false;
    }
    if (!unzipEnabled) {
      unzipPassword = "";
    }
  }

  // Load on mount (component is recreated each time the form opens)
  updateIsUnzipEnabled();

  function addDownload() {
    const urls = downloadUrl
      .split("\n")
      .map((url) => url.trim())
      .filter((url) => startsWithAnyProtocol(url, ALL_DOWNLOADABLE_PROTOCOLS));
    client.createTasks(urls, {
      path: selectedPath,
      unzipPassword: unzipPassword.trim() || undefined,
    });
    onClose();
  }
</script>

<div class="advanced-add-download-form">
  <textarea
    class="url-input input-field card"
    rows={2}
    bind:value={downloadUrl}
    placeholder={browser.i18n.getMessage("URLs_to_download_one_per_line")}
  ></textarea>
  <input
    type="password"
    class="input-field"
    bind:value={unzipPassword}
    disabled={!unzipEnabled}
    title={unzipEnabled
      ? undefined
      : browser.i18n.getMessage("Auto_Extract_service_is_disabled_in_Download_Station")}
    placeholder={browser.i18n.getMessage("Unzip_password")}
  />
  <div class="download-path card">
    <div class="path-display" title={selectedPath}>
      {browser.i18n.getMessage("Download_to")}
      <span class="path" class:faded={!selectedPath}>
        {selectedPath
          ? selectedPath.split("/").at(-1)
          : browser.i18n.getMessage("default_location")}
      </span>
    </div>
    <PathSelector
      onSelectPath={(path) => {
        selectedPath = path;
      }}
      {selectedPath}
      {client}
    />
  </div>
  <div class="buttons">
    <button onclick={onClose} title={browser.i18n.getMessage("Dont_add_a_new_task")}>
      <Icon name="xmark" size="lg" />
      {browser.i18n.getMessage("Cancel")}
    </button>
    <button
      onclick={addDownload}
      title={browser.i18n.getMessage("Download_the_above_URL_to_the_specified_location")}
      disabled={!hasDownloadUrl}
    >
      <Icon name="plus" size="lg" />
      {browser.i18n.getMessage("Add")}
    </button>
  </div>
</div>

<style>
  .advanced-add-download-form {
    display: flex;
    flex-direction: column;

    .card {
      border-radius: 2px;
      border: 1px solid #aaa;
      background-color: white;
    }

    .url-input {
      width: 100%;
      min-height: 30px;
      max-height: 180px;
      flex-shrink: 0;
      resize: vertical;
      field-sizing: content;
    }

    .input-field {
      padding-top: 5px;
      padding-bottom: 5px;
      margin-bottom: 5px;
    }

    .download-path {
      padding: 5px;
      flex: 1;
      display: flex;
      flex-direction: column;
      overflow-y: auto;

      .path-display {
        flex-shrink: 0;
        white-space: nowrap;
        overflow: hidden;
        text-overflow: ellipsis;
        margin-bottom: 3px;

        .path {
          margin-left: 3px;

          &.faded {
            color: #999;
          }
        }
      }
    }

    .buttons {
      text-align: right;
      padding: 4px 4px 0;
      flex-shrink: 0;

      button {
        margin: 5px 5px 0;
      }
    }
  }
</style>
