// src/common/components/DirectoryTree.tsx
import * as React from "react";
import classNames from "classnames";

export type DirectoryTreeFileChildren =
  | "unloaded"
  | { failureMessage: string }
  | DirectoryTreeFile[];

export interface DirectoryTreeFile {
  name: string;
  path: string;
  children: DirectoryTreeFileChildren;
}

export function isUnloadedChild(children: DirectoryTreeFileChildren): children is "unloaded" {
  return children === "unloaded";
}

export function isErrorChild(
  children: DirectoryTreeFileChildren,
): children is { failureMessage: string } {
  return (children as { failureMessage: string }).failureMessage != null;
}

export function isLoadedChild(
  children: DirectoryTreeFileChildren,
): children is DirectoryTreeFile[] {
  return !isUnloadedChild(children) && !isErrorChild(children);
}

export function recursivelyUpdateDirectoryTree(
  currentNode: DirectoryTreeFile,
  path: string,
  newChildren: DirectoryTreeFileChildren,
): DirectoryTreeFile {
  if (currentNode.path === path) {
    return {
      ...currentNode,
      children: newChildren,
    };
  } else if (!isLoadedChild(currentNode.children)) {
    console.error(
      `programmer error: tried to update tree at ${path} but ancestor ${currentNode.path} has no valid children; ancestor:`,
      currentNode,
    );
    return currentNode;
  } else {
    return {
      ...currentNode,
      children: currentNode.children.map(child => {
        if (path.startsWith(child.path)) {
          return recursivelyUpdateDirectoryTree(child, path, newChildren);
        } else {
          return child;
        }
      }),
    };
  }
}

export interface Props {
  file: DirectoryTreeFile;
  selectedPath?: string;
  requestLoad: (path: string) => void;
  onSelect: (path: string | undefined) => void;
}

export interface State {
  isExpanded: boolean;
}

export class DirectoryTree extends React.PureComponent<Props, State> {
  state: State = {
    isExpanded: false,
  };

  componentWillReceiveProps(nextProps: Props) {
    if (isErrorChild(nextProps.file.children)) {
      this.setState({ isExpanded: false });
    }
  }

  render() {
    const isPlaceholder =
      isLoadedChild(this.props.file.children) && this.props.file.children.length === 0;
    return (
      <div className="directory-tree">
        <div
          className={classNames("directory-header", {
            "is-selected": this.props.selectedPath === this.props.file.path,
          })}
        >
          <div
            className={classNames("directory-icon-wrapper", {
              placeholder: isPlaceholder,
              disabled: isErrorChild(this.props.file.children),
            })}
            onClick={isErrorChild(this.props.file.children) ? undefined : this.toggleExpanded}
            title={
              isErrorChild(this.props.file.children)
                ? this.props.file.children.failureMessage
                : browser.i18n.getMessage("Expandcollapse_directory")
            }
          >
            <span
              className={classNames("fa", {
                "fa-chevron-right expand-collapse":
                  isUnloadedChild(this.props.file.children) ||
                  (!isErrorChild(this.props.file.children) && this.props.file.children.length > 0),
                "fa-exclamation-triangle intent-warning": isErrorChild(this.props.file.children),
                "fa-fighter-jet": isPlaceholder,
                "is-expanded": this.state.isExpanded,
              })}
            />
          </div>
          <div className="name" onClick={this.onSelect} title={this.props.file.name}>
            {this.props.file.name}
          </div>
        </div>
        {this.renderChildren()}
      </div>
    );
  }

  private onSelect = () => {
    this.props.onSelect(this.props.file.path);
  };

  private toggleExpanded = () => {
    const isExpanded = !this.state.isExpanded;
    this.setState({ isExpanded });
    if (isExpanded && isUnloadedChild(this.props.file.children)) {
      this.props.requestLoad(this.props.file.path);
    }

    if (
      !isExpanded &&
      this.props.selectedPath &&
      this.props.selectedPath.startsWith(this.props.file.path)
    ) {
      this.props.onSelect(undefined);
    }
  };

  private renderChildren(): React.ReactNode {
    if (this.state.isExpanded) {
      if (isUnloadedChild(this.props.file.children)) {
        return <div className="children loading">{browser.i18n.getMessage("Loading")}</div>;
      } else if (isErrorChild(this.props.file.children)) {
        return null;
      } else if (this.props.file.children.length === 0) {
        return null;
      } else {
        return (
          <ul className="children loaded">
            {this.props.file.children.map(child => (
              <DirectoryTree
                key={child.path}
                file={child}
                requestLoad={this.props.requestLoad}
                selectedPath={this.props.selectedPath}
                onSelect={this.props.onSelect}
              />
            ))}
          </ul>
        );
      }
    } else {
      return null;
    }
  }
}

// src/popup/DirectoryTree.svelte
<script lang="ts">
  import Icon from "../common/components/Icon.svelte";
  import DirectoryTree from "./DirectoryTree.svelte";
  import {
    type DirectoryTreeFile,
    isUnloadedChild,
    isErrorChild,
    isLoadedChild,
  } from "./directoryTreeHelpers";

  interface Props {
    file: DirectoryTreeFile;
    selectedPath?: string;
    requestLoad: (path: string) => void;
    onSelect: (path: string | undefined) => void;
  }

  let { file, selectedPath, requestLoad, onSelect }: Props = $props();

  let isExpanded = $state(false);

  $effect(() => {
    if (isErrorChild(file.children)) {
      isExpanded = false;
    }
  });

  function toggleExpanded() {
    const nextExpanded = !isExpanded;
    isExpanded = nextExpanded;
    if (nextExpanded && isUnloadedChild(file.children)) {
      requestLoad(file.path);
    }
    if (!nextExpanded && selectedPath && selectedPath.startsWith(file.path)) {
      onSelect(undefined);
    }
  }

  let isPlaceholder = $derived(isLoadedChild(file.children) && file.children.length === 0);
  let isError = $derived(isErrorChild(file.children));
  let isChevron = $derived(
    isUnloadedChild(file.children) ||
      (!isError && isLoadedChild(file.children) && file.children.length > 0),
  );
</script>

<div class="directory-tree">
  <div class="directory-header" class:is-selected={selectedPath === file.path}>
    <div
      class="directory-icon-wrapper"
      class:placeholder={isPlaceholder}
      class:disabled={isError}
      onclick={isError ? undefined : toggleExpanded}
      role="button"
      tabindex="0"
      onkeydown={(e) => {
        if (e.key === "Enter" && !isError) toggleExpanded();
      }}
      title={isErrorChild(file.children)
        ? file.children.failureMessage
        : browser.i18n.getMessage("Expandcollapse_directory")}
    >
      <span
        class:expand-collapse={isChevron}
        class:intent-warning={isError}
        class:is-expanded={isExpanded}
      >
        {#if isError}
          <Icon name="triangle-exclamation" />
        {:else if isPlaceholder}
          <Icon name="jet-fighter" />
        {:else}
          <Icon name="chevron-right" />
        {/if}
      </span>
    </div>
    <div
      class="name"
      onclick={() => onSelect(file.path)}
      role="button"
      tabindex="0"
      onkeydown={(e) => {
        if (e.key === "Enter") onSelect(file.path);
      }}
      title={file.name}
    >
      {file.name}
    </div>
  </div>
  {#if isExpanded}
    {#if isUnloadedChild(file.children)}
      <div class="children loading">{browser.i18n.getMessage("Loading")}</div>
    {:else if !isErrorChild(file.children) && file.children.length > 0}
      <ul class="children loaded">
        {#each file.children as child (child.path)}
          <DirectoryTree file={child} {requestLoad} {selectedPath} {onSelect} />
        {/each}
      </ul>
    {/if}
  {/if}
</div>

<style>
  .directory-tree {
    --icon-size: 20px;
    --icon-text-margin: 3px;

    &:not(:last-child) {
      margin-top: 1px;
    }

    .directory-header {
      display: flex;
      align-items: center;
      justify-content: center;
      height: var(--icon-size);

      .name {
        flex: 1;
        white-space: nowrap;
        overflow: hidden;
        text-overflow: ellipsis;
        border-radius: 2px;
        padding: 2px var(--icon-text-margin);

        &:hover {
          color: white;
          background-color: var(--color-selected);
          cursor: pointer;
        }
      }

      .directory-icon-wrapper {
        width: var(--icon-size);
        height: var(--icon-size);
        transition: background-color 100ms;
        border-radius: 2px;
        line-height: var(--icon-size);
        text-align: center;

        &.placeholder :global(.icon) {
          visibility: hidden;
        }

        :global(.icon) {
          font-size: 0.8em;
        }

        .expand-collapse {
          display: inline-block;
          transition: transform 100ms;

          &.is-expanded {
            transform: rotate(90deg);
          }
        }

        &:not(.placeholder):not(.disabled):hover {
          cursor: pointer;
          background-color: rgba(0, 0, 0, 0.1);
        }

        &.disabled {
          color: var(--color-text-faded);
        }
      }

      &.is-selected .name {
        color: white;
        background-color: var(--color-selected);
      }
    }

    > .children {
      padding: 2px 0 2px calc(var(--icon-size) + var(--icon-text-margin));

      &.loaded {
        margin: 0;
        list-style: none;
      }

      &.loading {
        font-style: italic;
        color: #999;
      }
    }
  }
</style>
