// src/popup/Header.svelte
<script lang="ts">
  import Icon from "../common/components/Icon.svelte";

  interface Props {
    isAddingDownload: boolean;
    onClickAddDownload?: () => void;
    completedTaskCount: number;
    onClickClearTasks?: "pending" | (() => void);
    onClickOpenDownloadStationUi?: () => void;
    isShowingDisplaySettings: boolean;
    onClickDisplaySettings: () => void;
    isMissingConfig: boolean;
    showDropShadow: boolean;
    disabledLogo: boolean;
  }

  let {
    isAddingDownload,
    onClickAddDownload,
    completedTaskCount,
    onClickClearTasks,
    onClickOpenDownloadStationUi,
    isShowingDisplaySettings,
    onClickDisplaySettings,
    isMissingConfig,
    showDropShadow,
    disabledLogo,
  }: Props = $props();

  let addDisabled = $derived(onClickAddDownload == null);
  let clearDisabled = $derived(
    onClickClearTasks === "pending" || onClickClearTasks == null || completedTaskCount === 0,
  );
  let openDisabled = $derived(onClickOpenDownloadStationUi == null);
</script>

<header class:with-shadow={showDropShadow}>
  <img
    src={disabledLogo ? "/icons/icon-64-disabled.png" : "/icons/icon-64.png"}
    alt="NAS Download Manager"
  />
  <span class="extension-name">NAS Download Manager</span>
  <button
    onclick={onClickAddDownload}
    title={browser.i18n.getMessage("Add_download")}
    disabled={addDisabled}
    class:active={isAddingDownload}
  >
    <Icon name="plus" size="lg" />
  </button>
  <button
    onclick={onClickClearTasks === "pending" ? undefined : onClickClearTasks}
    title={browser.i18n.getMessage("Clear_ZcountZ_completed_and_not_uploading_tasks", [
      completedTaskCount,
    ])}
    disabled={clearDisabled}
  >
    {#if onClickClearTasks === "pending"}
      <Icon name="arrows-rotate" size="lg" spin />
    {:else}
      <Icon name="broom" size="lg" />
    {/if}
  </button>
  <button
    onclick={onClickOpenDownloadStationUi}
    title={browser.i18n.getMessage("Open_DownloadStation_UI")}
    disabled={openDisabled}
  >
    <Icon name="up-right-from-square" size="lg" />
  </button>
  <button
    onclick={onClickDisplaySettings}
    title={browser.i18n.getMessage("Show_task_display_settings")}
    class:active={isShowingDisplaySettings}
  >
    <Icon name="filter" size="lg" />
  </button>
  <button
    onclick={() => browser.runtime.openOptionsPage()}
    title={browser.i18n.getMessage("Open_settings")}
    class:called-out={isMissingConfig}
  >
    <Icon name="gear" size="lg" />
  </button>
</header>

<style>
  header {
    flex-shrink: 0;
    white-space: nowrap;
    display: flex;
    align-items: center;
    padding: 5px;
    transition: box-shadow 100ms;
    border-bottom: 1px solid rgba(0, 0, 0, 0.2);
    box-shadow: 0 1px 2px 2px rgba(0, 0, 0, 0);

    img {
      width: 24px;
      height: 24px;
      margin-right: 4px;
    }

    .extension-name {
      margin-right: auto;
      font-weight: 500;
    }

    button {
      margin-left: 2px;

      &.called-out {
        animation-name: shadow-glow;
        animation-duration: 1s;
        animation-iteration-count: infinite;
        animation-timing-function: ease-in-out;
        animation-direction: alternate;
      }
    }

    &.with-shadow {
      box-shadow: 0 1px 2px 2px rgba(0, 0, 0, 0.2);
    }
  }

  @keyframes shadow-glow {
    0% {
      box-shadow: 0 0 2px 2px rgba(19, 124, 189, 0);
    }
    100% {
      box-shadow: 0 0 2px 2px rgba(19, 124, 189, 0.7);
    }
  }
</style>

// src/popup/Header.tsx
import "./header.css";
import classNames from "classnames";

import { disabledPropAndClassName } from "../common/classnameUtil";

export interface Props {
  isAddingDownload: boolean;
  onClickAddDownload?: () => void;
  completedTaskCount: number;
  onClickClearTasks?: "pending" | (() => void);
  onClickOpenDownloadStationUi?: () => void;
  isShowingDisplaySettings: boolean;
  onClickDisplaySettings: () => void;
  isMissingConfig: boolean;
  showDropShadow: boolean;
  disabledLogo: boolean;
}

export function Header(props: Props) {
  return (
    <header className={classNames({ "with-shadow": props.showDropShadow })}>
      <img src={props.disabledLogo ? "/icons/icon-64-disabled.png" : "/icons/icon-64.png"} />
      <span className="extension-name">NAS Download Manager</span>
      <button
        onClick={props.onClickAddDownload}
        title={browser.i18n.getMessage("Add_download")}
        {...disabledPropAndClassName(
          props.onClickAddDownload == null,
          classNames({ active: props.isAddingDownload }),
        )}
      >
        <div className="fa fa-lg fa-plus" />
      </button>
      <button
        onClick={props.onClickClearTasks === "pending" ? undefined : props.onClickClearTasks}
        title={browser.i18n.getMessage("Clear_ZcountZ_completed_and_not_uploading_tasks", [
          props.completedTaskCount,
        ])}
        {...disabledPropAndClassName(
          props.onClickClearTasks === "pending" ||
            props.onClickClearTasks == null ||
            props.completedTaskCount === 0,
        )}
      >
        <div
          className={
            props.onClickClearTasks === "pending" ? "fa fa-lg fa-sync fa-spin" : "fa fa-lg fa-broom"
          }
        />
      </button>
      <button
        onClick={props.onClickOpenDownloadStationUi}
        title={browser.i18n.getMessage("Open_DownloadStation_UI")}
        {...disabledPropAndClassName(props.onClickOpenDownloadStationUi == null)}
      >
        <div className="fa fa-lg fa-external-link-alt" />
      </button>
      <button
        onClick={props.onClickDisplaySettings}
        title={browser.i18n.getMessage("Show_task_display_settings")}
        className={classNames({ active: props.isShowingDisplaySettings })}
      >
        <div className="fa fa-lg fa-filter" />
      </button>
      <button
        onClick={() => {
          browser.runtime.openOptionsPage();
        }}
        title={browser.i18n.getMessage("Open_settings")}
        className={classNames({ "called-out": props.isMissingConfig })}
      >
        <div className="fa fa-lg fa-cog" />
      </button>
    </header>
  );
}
