// src/popup/Popup.svelte
<script lang="ts">
  import Icon from "../common/components/Icon.svelte";
  import type { DownloadStationTask } from "../common/apis/synology/DownloadStation/Task";
  import type {
    VisibleTaskSettings,
    TaskSortType,
    BadgeDisplayType,
  } from "../common/state/defaults";
  import { sortTasks, filterTasks } from "../common/filtering";
  import TaskFilterSettingsForm from "../common/components/TaskFilterSettingsForm.svelte";
  import NonIdealState from "../common/components/NonIdealState.svelte";
  import type { PopupClient } from "./popupClient";
  import AdvancedAddDownloadForm from "./AdvancedAddDownloadForm.svelte";
  import Header from "./Header.svelte";
  import Footer from "./Footer.svelte";
  import Task from "./Task.svelte";
  import PasswordForm from "./PasswordForm.svelte";

  interface Props {
    tasks: DownloadStationTask[];
    taskFetchFailureReason: "missing-config" | "login-required" | { failureMessage: string } | null;
    tasksLastInitiatedFetchTimestamp: number | null;
    tasksLastCompletedFetchTimestamp: number | null;
    visibleTasks: VisibleTaskSettings;
    changeVisibleTasks: (visibleTasks: VisibleTaskSettings) => void;
    taskSort: TaskSortType;
    changeTaskSort: (sort: TaskSortType) => void;
    badgeDisplay: BadgeDisplayType;
    changeBadgeDisplay: (display: BadgeDisplayType) => void;
    showInactiveTasks: boolean;
    changeShowInactiveTasks: (show: boolean) => void;
    client?: PopupClient;
  }

  let {
    tasks,
    taskFetchFailureReason,
    tasksLastInitiatedFetchTimestamp,
    tasksLastCompletedFetchTimestamp,
    visibleTasks,
    changeVisibleTasks,
    taskSort,
    changeTaskSort,
    badgeDisplay,
    changeBadgeDisplay,
    showInactiveTasks,
    changeShowInactiveTasks,
    client,
  }: Props = $props();

  let isShowingDropShadow = $state(false);
  let isAddingDownload = $state(false);
  let isShowingDisplaySettings = $state(false);
  let isClearingCompletedTasks = $state(false);
  let bodyRef: HTMLElement | undefined;
  let scrollTimer: ReturnType<typeof setTimeout> | undefined;

  let completedTaskIds = $derived(tasks.filter((t) => t.status === "finished").map((t) => t.id));

  let onClickClearTasks = $derived.by(() => {
    if (!client) return undefined;
    return async () => {
      isClearingCompletedTasks = true;
      await client!.deleteTasks(completedTaskIds);
      isClearingCompletedTasks = false;
    };
  });

  let canAddDownload = $derived(client != null && taskFetchFailureReason !== "login-required");

  let filteredTasks = $derived(filterTasks(tasks, visibleTasks, showInactiveTasks));
  let sortedTasks = $derived(sortTasks(filteredTasks, taskSort));
  let hiddenTaskCount = $derived(tasks.length - filteredTasks.length);

  function updateTaskTypeVisibility(taskType: keyof VisibleTaskSettings, visibility: boolean) {
    changeVisibleTasks({ ...visibleTasks, [taskType]: visibility });
  }

  function onBodyScroll() {
    if (scrollTimer != null) return;
    scrollTimer = setTimeout(() => {
      scrollTimer = undefined;
      isShowingDropShadow = bodyRef ? bodyRef.scrollTop !== 0 : false;
    }, 200);
  }

  // Cleanup scroll timer on destroy
  $effect(() => {
    return () => {
      clearTimeout(scrollTimer);
    };
  });

  function deleteTask(taskId: string) {
    return client!.deleteTasks([taskId]);
  }
</script>

<div class="popup">
  <Header
    {isAddingDownload}
    onClickAddDownload={canAddDownload
      ? () => {
          isAddingDownload = !isAddingDownload;
          isShowingDisplaySettings = false;
        }
      : undefined}
    completedTaskCount={completedTaskIds.length}
    onClickClearTasks={isClearingCompletedTasks ? "pending" : onClickClearTasks}
    onClickOpenDownloadStationUi={client?.openDownloadStationUi}
    {isShowingDisplaySettings}
    onClickDisplaySettings={() => {
      isShowingDisplaySettings = !isShowingDisplaySettings;
      isAddingDownload = false;
    }}
    isMissingConfig={taskFetchFailureReason === "missing-config"}
    showDropShadow={isShowingDropShadow}
    disabledLogo={taskFetchFailureReason != null}
  />
  <div class="display-settings" class:is-visible={isShowingDisplaySettings}>
    <h4 class="title">{browser.i18n.getMessage("Task_Display_Settings")}</h4>
    <TaskFilterSettingsForm
      {visibleTasks}
      taskSortType={taskSort}
      badgeDisplayType={badgeDisplay}
      {showInactiveTasks}
      {updateTaskTypeVisibility}
      updateTaskSortType={changeTaskSort}
      updateBadgeDisplayType={changeBadgeDisplay}
      updateShowInactiveTasks={changeShowInactiveTasks}
    />
  </div>
  <div
    class="popup-body"
    class:with-foreground={isAddingDownload}
    onscroll={onBodyScroll}
    bind:this={bodyRef}
  >
    <!-- Task list -->
    {#if taskFetchFailureReason === "missing-config"}
      <NonIdealState
        text={browser.i18n.getMessage("Configure_your_hostname_username_and_password_in_settings")}
      >
        {#snippet icon()}<Icon name="gear" size="2x" />{/snippet}
      </NonIdealState>
    {:else if taskFetchFailureReason === "login-required"}
      {#if !client}
        <NonIdealState />
      {:else}
        <NonIdealState text={browser.i18n.getMessage("Password_required")}>
          {#snippet icon()}<Icon name="lock" size="2x" />{/snippet}
          <PasswordForm {client} />
        </NonIdealState>
      {/if}
    {:else if tasksLastCompletedFetchTimestamp == null}
      <NonIdealState>
        {#snippet icon()}<Icon name="arrows-rotate" size="2x" spin />{/snippet}
      </NonIdealState>
    {:else if tasks.length === 0}
      <NonIdealState text={browser.i18n.getMessage("No_download_tasks")} />
    {:else if filteredTasks.length === 0}
      <NonIdealState
        text={browser.i18n.getMessage("Download_tasks_exist_but_none_match_your_filters")}
      >
        {#snippet icon()}<Icon name="filter" size="2x" />{/snippet}
      </NonIdealState>
    {:else}
      <div class="download-tasks">
        <ul>
          {#each sortedTasks as task (task.id)}
            <Task
              {task}
              onDelete={client ? deleteTask : undefined}
              onPause={client?.pauseTask}
              onResume={client?.resumeTask}
            />
          {/each}
        </ul>
        {#if hiddenTaskCount > 0}
          <div
            class="hidden-count"
            onclick={() => {
              isShowingDisplaySettings = true;
            }}
            role="button"
            tabindex="0"
            onkeydown={(e) => {
              if (e.key === "Enter") isShowingDisplaySettings = true;
            }}
          >
            {browser.i18n.getMessage("and_ZcountZ_more_tasks_hidden_by_filters", [hiddenTaskCount])}
          </div>
        {/if}
      </div>
    {/if}

    <!-- Add download overlay -->
    {#if isAddingDownload && client}
      <div class="add-download-overlay">
        <div class="backdrop"></div>
        <div class="overlay-content">
          <AdvancedAddDownloadForm
            onClose={() => {
              isAddingDownload = false;
            }}
            {client}
          />
        </div>
      </div>
    {/if}
  </div>
  <Footer
    {tasks}
    {taskFetchFailureReason}
    {tasksLastInitiatedFetchTimestamp}
    {tasksLastCompletedFetchTimestamp}
  />
</div>

<style>
  .popup {
    display: flex;
    flex-direction: column;

    .display-settings {
      flex-shrink: 0;
      max-height: 0px;
      /* If Firefox fails to reflow after this transition, try:
         1. interpolate-size: allow-keywords on the container
         2. bind:clientHeight with explicit height instead of max-height
         3. As last resort, a nonce-based forced rerender via $effect */
      transition: max-height 300ms;
      overflow: hidden;

      &.is-visible {
        max-height: 1000px;
        border-bottom: 1px solid rgba(0, 0, 0, 0.2);
      }

      h4 {
        margin-left: 15px;
      }

      :global(.task-filter-settings-form select) {
        margin-right: 15px;
      }
    }

    .popup-body {
      flex: 1;
      overflow-y: auto;
      position: relative;
      min-height: 50px;

      &.with-foreground {
        min-height: 400px;

        > :not(.add-download-overlay) {
          filter: blur(3px);
        }

        .download-tasks {
          overflow-y: hidden;
          height: 100%;
        }
      }
    }
  }

  .download-tasks {
    .hidden-count {
      flex: 1;
      display: flex;
      justify-content: center;
      align-items: center;
      margin-top: 5px;
      margin-bottom: 10px;

      &:hover {
        text-decoration: underline;
        cursor: pointer;
      }
    }

    ul {
      list-style: none;
      margin: 0;
      padding: 0;
    }
  }

  .popup-body .add-download-overlay {
    position: absolute;
    top: 0;
    bottom: 0;
    left: 0;
    right: 0;

    .backdrop {
      width: 100%;
      height: 100%;
      background-color: rgba(0, 0, 0, 0.2);
      filter: blur(0.5px);
    }

    .overlay-content {
      position: absolute;
      top: 0;
      left: 0;
      right: 0;
      bottom: 0;
      padding: 10px;
    }

    :global(.advanced-add-download-form) {
      height: 100%;

      :global(.download-path) {
        flex: 1;
      }
    }
  }
</style>

// src/popup/index.tsx
import '../common/sideEffectingInit';
import * as React from 'react';
import * as ReactDOM from 'react-dom';
import * as momentProxy from 'moment';
import * as classNamesProxy from 'classnames';
import debounce from 'lodash-es/debounce';
import { SynologyResponse, DownloadStationTask, ApiClient } from 'synology-typescript-api';

// https://github.com/rollup/rollup/issues/1267
const moment: typeof momentProxy = (momentProxy as any).default || momentProxy;
const classNames: typeof classNamesProxy = (classNamesProxy as any).default || classNamesProxy;

import { AdvancedAddDownloadForm } from '../common/components/AdvancedAddDownloadForm';
import {
  Settings,
  VisibleTaskSettings,
  TaskSortType,
  onStoredStateChange,
  getHostUrl
} from '../common/state';
import { onUnhandledError } from '../common/errorHandlers';
import { getSharedObjects } from '../common/apis/messages';
import { addDownloadTaskAndPoll, pollTasks } from '../common/apis/actions';
import { CallbackResponse } from './popupTypes';
import { matchesFilter, sortTasks } from './filtering';
import { Task } from './Task';
import { NoTasks } from './NoTasks';
import { FatalError } from './FatalError';
import { FatalErrorWrapper } from './FatalErrorWrapper';
import { errorMessageFromCode } from '../common/apis/errors';
import { TaskFilterSettingsForm } from '../common/components/TaskFilterSettingsForm';

function disabledPropAndClassName(disabled: boolean, className?: string) {
  return {
    disabled,
    className: classNames({ 'disabled': disabled }, className)
  };
}

interface PopupProps {
  api: ApiClient;
  tasks: DownloadStationTask[];
  taskFetchFailureReason: 'missing-config' | { failureMessage: string } | null;
  tasksLastInitiatedFetchTimestamp: number | null;
  tasksLastCompletedFetchTimestamp: number | null;
  visibleTasks: VisibleTaskSettings;
  changeVisibleTasks: (visibleTasks: VisibleTaskSettings) => void;
  taskSort: TaskSortType;
  changeTaskSort: (sort: TaskSortType) => void;
  openDownloadStationUi?: () => void;
  createTask?: (url: string, path?: string) => Promise<void>;
  pauseTask?: (taskId: string) => Promise<CallbackResponse>;
  resumeTask?: (taskId: string) => Promise<CallbackResponse>;
  deleteTasks?: (taskIds: string[]) => Promise<CallbackResponse>;
}

interface State {
  isShowingDropShadow: boolean;
  isAddingDownload: boolean;
  isShowingDisplaySettings: boolean;
  isClearingCompletedTasks: boolean;
  // Bleh. If a popup grows larger in Firefox, it will leave it as such until the DOM changes and causes
  // a relayout. Therefore, after collapsing the filter panel, we want to force a layout to make it the right
  // size again. Unfortunately we can't do that by just reading a layout property like offsetHeight, we have
  // to actually change the DOM, hence we render this invisible nonce whenever we toggle the panel.
  firefoxRerenderNonce: number;
}

class Popup extends React.PureComponent<PopupProps, State> {
  private bodyRef?: HTMLElement;

  state: State = {
    isShowingDropShadow: false,
    isAddingDownload: false,
    isShowingDisplaySettings: false,
    isClearingCompletedTasks: false,
    firefoxRerenderNonce: 0
  };

  render() {
    return (
      <div className='popup'>
        {this.renderHeader()}
        {this.renderDisplaySettings()}
        <div className={classNames('popup-body', { 'with-foreground': this.state.isAddingDownload })}>
          {this.renderTaskList()}
          {this.maybeRenderAddDownloadOverlay()}
        </div>
        <div style={{ display: 'none' }}>{this.state.firefoxRerenderNonce}</div>
      </div>
    );
  }

  private renderHeader() {
    let text: string;
    let tooltip: string;
    let classes: string | undefined = undefined;
    let leftIcon: string;
    let rightIcon: string | undefined = undefined;

    if (this.props.taskFetchFailureReason === 'missing-config') {
      text = browser.i18n.getMessage('Settings_unconfigured');
      tooltip = browser.i18n.getMessage('The_hostname_username_or_password_are_not_configured');
      leftIcon = 'fa-gear';
    } else if (this.props.tasksLastCompletedFetchTimestamp == null) {
      text = browser.i18n.getMessage('Updating');
      tooltip = browser.i18n.getMessage('Updating_download_tasks');
      leftIcon = 'fa-refresh fa-spin';
    } else if (this.props.taskFetchFailureReason != null) {
      text = browser.i18n.getMessage('Error_updating_tasks');
      tooltip = this.props.taskFetchFailureReason.failureMessage;
      classes = 'intent-error';
      leftIcon = 'fa-exclamation-triangle';
      rightIcon = 'fa-info-circle';
    } else {
      text = browser.i18n.getMessage('Updated_ZtimeZ', [ moment(this.props.tasksLastCompletedFetchTimestamp).fromNow() ]);
      tooltip = moment(this.props.tasksLastCompletedFetchTimestamp).format('ll LTS');
      classes = 'intent-success';
      leftIcon = 'fa-check';
    }

    if (
      this.props.tasksLastInitiatedFetchTimestamp != null &&
      this.props.tasksLastCompletedFetchTimestamp != null &&
      this.props.tasksLastInitiatedFetchTimestamp > this.props.tasksLastCompletedFetchTimestamp
    ) {
      leftIcon = 'fa-refresh fa-spin';
      tooltip += ' ' + browser.i18n.getMessage('updating_now');
    }

    return (
      <header className={classNames({ 'with-shadow': this.state.isShowingDropShadow })}>
        <div className={classNames('description', classes)} title={tooltip}>
          <span className={classNames('left-icon fa', leftIcon)}/>
          {text}
          {rightIcon && <span className={classNames('right-icon fa', rightIcon)}/>}
        </div>
        <button
          onClick={() => { this.setState({ isAddingDownload: !this.state.isAddingDownload }); }}
          title={browser.i18n.getMessage('Add_download')}
          {...disabledPropAndClassName(this.props.createTask == null)}
        >
          <div className='fa fa-lg fa-plus'/>
        </button>
        <button
          onClick={this.props.openDownloadStationUi}
          title={browser.i18n.getMessage('Open_DownloadStation_UI')}
          {...disabledPropAndClassName(this.props.openDownloadStationUi == null)}
        >
          <div className='fa fa-lg fa-share-square-o'/>
        </button>
        <button
          onClick={() => { this.setState({ isShowingDisplaySettings: !this.state.isShowingDisplaySettings }); }}
          title={browser.i18n.getMessage('Show_task_display_settings')}
          className={classNames({ 'active': this.state.isShowingDisplaySettings })}
        >
          <div className='fa fa-lg fa-filter'/>
        </button>
        <button
          onClick={() => { browser.runtime.openOptionsPage(); }}
          title={browser.i18n.getMessage('Open_settings')}
          className={classNames({ 'called-out': this.props.taskFetchFailureReason === 'missing-config' })}
        >
          <div className='fa fa-lg fa-cog'/>
        </button>
      </header>
    );
  }

  private renderDisplaySettings() {
      const completedTaskIds = this.props.tasks.filter(t => t.status === 'finished').map(t => t.id);
      const deleteTasks = this.props.deleteTasks
        ? () => {
          this.setState({ isClearingCompletedTasks: true });
          this.props.deleteTasks!(completedTaskIds)
            .then(() => {
              this.setState({ isClearingCompletedTasks: false });
            });
        }
        : undefined;
      return (
        <div className={classNames('display-settings', { 'is-visible': this.state.isShowingDisplaySettings })}>
          <h4 className='title'>{browser.i18n.getMessage('Task_Display_Settings')}</h4>
          <TaskFilterSettingsForm
            visibleTasks={this.props.visibleTasks}
            taskSortType={this.props.taskSort}
            updateTaskTypeVisibility={this.updateTaskTypeVisibility}
            updateTaskSortType={this.props.changeTaskSort}
          />
          <button
            onClick={deleteTasks}
            title={browser.i18n.getMessage('Clear_tasks_that_are_completed_and_not_currently_uploading')}
            {...disabledPropAndClassName(
              this.state.isClearingCompletedTasks || deleteTasks == null || completedTaskIds.length === 0,
              'clear-completed-tasks-button'
            )}
          >
            {browser.i18n.getMessage('Clear_ZcountZ_Completed_Tasks', [ completedTaskIds.length ])}
            {this.state.isClearingCompletedTasks && <span className='fa fa-spin fa-refresh'/>}
          </button>
        </div>
      );
  }

  private updateTaskTypeVisibility = (taskType: keyof VisibleTaskSettings, visibility: boolean) => {
    this.props.changeVisibleTasks({
      ...this.props.visibleTasks,
      [taskType]: visibility
    });
  };

  private renderTaskList() {
    if (this.props.taskFetchFailureReason === 'missing-config') {
      return <NoTasks icon='fa-gear' text={browser.i18n.getMessage('Configure_your_hostname_username_and_password_in_settings')}/>;
    } else if (this.props.tasksLastCompletedFetchTimestamp == null) {
      return <NoTasks icon='fa-refresh fa-spin'/>;
    } else if (this.props.tasks.length === 0) {
      return <NoTasks icon='fa-circle-o' text={browser.i18n.getMessage('No_download_tasks')}/>;
    } else {
      const filteredTasks = this.props.tasks.filter(t =>
        (this.props.visibleTasks.downloading && matchesFilter(t, 'downloading')) ||
        (this.props.visibleTasks.uploading && matchesFilter(t, 'uploading')) ||
        (this.props.visibleTasks.completed && matchesFilter(t, 'completed')) ||
        (this.props.visibleTasks.errored && matchesFilter(t, 'errored')) ||
        (this.props.visibleTasks.other && matchesFilter(t, 'other'))
      );
      if (filteredTasks.length === 0) {
        return <NoTasks icon='fa-filter' text={browser.i18n.getMessage('Download_tasks_exist_but_none_match_your_filters')}/>;
      } else {
        const hiddenTaskCount = this.props.tasks.length - filteredTasks.length;
        const deleteTask = this.props.deleteTasks ? ((taskId: string) => this.props.deleteTasks!([ taskId ])) : undefined;
        return (
          <div className='download-tasks'>
            <ul
              onScroll={this.onBodyScroll}
              ref={e => { this.bodyRef = e || undefined; }}
            >
              {sortTasks(filteredTasks, this.props.taskSort).map(task => (
                <Task
                  key={task.id}
                  task={task}
                  onDelete={deleteTask}
                  onPause={this.props.pauseTask}
                  onResume={this.props.resumeTask}
                />
              ))}
            </ul>
            {hiddenTaskCount > 0 && (
              <div
                className='hidden-count'
                onClick={() => { this.setState({ isShowingDisplaySettings: true }); }}
              >
                {browser.i18n.getMessage('and_ZcountZ_more_hidden_tasks', [ hiddenTaskCount ])}
              </div>
            )}
          </div>
        );
      }
    }
  }

  private maybeRenderAddDownloadOverlay() {
    if (this.state.isAddingDownload) {
      return (
        <div className='add-download-overlay'>
          <div className='backdrop'/>
          <div className='overlay-content'>
            <AdvancedAddDownloadForm
              client={this.props.api}
              onCancel={() => { this.setState({ isAddingDownload: false }); }}
              onAddDownload={(url, path) => {
                this.props.createTask!(url, path);
                this.setState({ isAddingDownload: false });
              }}
            />
          </div>
        </div>
      );
    } else {
      return null;
    }
  }

  private onBodyScroll = debounce(() => {
    if (this.bodyRef) {
      this.setState({ isShowingDropShadow: this.bodyRef.scrollTop !== 0 })
    } else {
      this.setState({ isShowingDropShadow: false });
    }
  }, 100);

  componentDidUpdate(_prevProps: PopupProps, prevState: State) {
    if (prevState.isShowingDisplaySettings !== this.state.isShowingDisplaySettings) {
      setTimeout(() => {
        this.setState({ firefoxRerenderNonce: this.state.firefoxRerenderNonce + 1 });
      }, 350);
    }
  }
}

const PrivateBrowsingUnsupported = () => (
  <div className='popup'>
    <NoTasks
      icon='fa-user-secret'
      text={browser.i18n.getMessage('Private_browsing_mode_is_not_currently_supported')}
    />
  </div>
);

const ELEMENT = document.getElementById('body')!;

getSharedObjects()
  .then(objects => {
    if (objects) {
      const { api } = objects;

      pollTasks(api);
      setInterval(() => { pollTasks(api); }, 10000);

      function convertResponse(response: SynologyResponse<any>): CallbackResponse {
        if (response.success) {
          return 'success';
        } else {
          const reason = errorMessageFromCode(response.error.code, 'DownloadStation.Task');
          console.error(`API call failed, reason: ${reason}`);
          return { failMessage: reason };
        }
      }

      function reloadOnSuccess(response: CallbackResponse): Promise<CallbackResponse> {
        if (response === 'success') {
          return pollTasks(api)
            .then(() => response);
        } else {
          return Promise.resolve(response);
        }
      }

      function changeVisibleTasks(visibleTasks: VisibleTaskSettings) {
        // Assign to intermediate so compiler can help with safety.
        const partialSettings: Partial<Settings> = { visibleTasks };
        browser.storage.local.set(partialSettings);
      }

      function changeSortType(taskSortType: TaskSortType) {
        // Assign to intermediate so compiler can help with safety.
        const partialSettings: Partial<Settings> = { taskSortType };
        browser.storage.local.set(partialSettings);
      }

      onStoredStateChange(storedState => {

        const hostUrl = getHostUrl(storedState.connection);

        const openDownloadStationUi = hostUrl
          ? () => {
              browser.tabs.create({
                url: hostUrl + '/index.cgi?launchApp=SYNO.SDS.DownloadStation.Application',
                active: true
              });
            }
          : undefined;

        const createTask = hostUrl
          ? (url: string, path?: string) => {
              return addDownloadTaskAndPoll(api, storedState.notifications.enableFeedbackNotifications, url, path);
            }
          : undefined;

        const pauseTask = hostUrl
          ? (taskId: string) => {
              return api.DownloadStation.Task.Pause({ id: [ taskId ] })
                .then(convertResponse)
                .then(reloadOnSuccess);
            }
          : undefined;

        const resumeTask = hostUrl
          ? (taskId: string) => {
              return api.DownloadStation.Task.Resume({ id: [ taskId ] })
                .then(convertResponse)
                .then(reloadOnSuccess);
            }
          : undefined;

        const deleteTasks = hostUrl
          ? (taskIds: string[]) => {
              return api.DownloadStation.Task.Delete({
                id: taskIds,
                force_complete: false
              })
                .then(convertResponse)
                .then(reloadOnSuccess);
            }
          : undefined;

        ReactDOM.render(
          <FatalErrorWrapper>
            <Popup
              api={api}
              tasks={storedState.tasks}
              taskFetchFailureReason={storedState.taskFetchFailureReason}
              tasksLastInitiatedFetchTimestamp={storedState.tasksLastInitiatedFetchTimestamp}
              tasksLastCompletedFetchTimestamp={storedState.tasksLastCompletedFetchTimestamp}
              visibleTasks={storedState.visibleTasks}
              changeVisibleTasks={changeVisibleTasks}
              taskSort={storedState.taskSortType}
              changeTaskSort={changeSortType}
              openDownloadStationUi={openDownloadStationUi}
              createTask={createTask}
              pauseTask={pauseTask}
              resumeTask={resumeTask}
              deleteTasks={deleteTasks}
            />
          </FatalErrorWrapper>
        , ELEMENT);
      });
    } else {
      ReactDOM.render(<PrivateBrowsingUnsupported/>, ELEMENT);
    }
  })
  .catch(e => {
    onUnhandledError(e);
    ReactDOM.render(<FatalError error={e}/>, ELEMENT);
  });
