// src/popup/PopupWrapper.svelte
<script lang="ts">
  import { store } from "../common/state/store.svelte";
  import { getClient } from "./popupClient";
  import Popup from "./Popup.svelte";
  import type {
    Settings,
    VisibleTaskSettings,
    TaskSortType,
    BadgeDisplayType,
  } from "../common/state/defaults";

  let state = $derived(store.current);
  let settings = $derived(state?.settings);
  let client = $derived(settings?.connection ? getClient(settings.connection) : undefined);

  function updateSettings(patch: Partial<Settings>) {
    if (!settings) return;
    browser.storage.local.set({ settings: { ...settings, ...patch } });
  }
</script>

{#if state?.settings}
  <Popup
    tasks={state.tasks ?? []}
    taskFetchFailureReason={state.taskFetchFailureReason ?? null}
    tasksLastInitiatedFetchTimestamp={state.tasksLastInitiatedFetchTimestamp ?? null}
    tasksLastCompletedFetchTimestamp={state.tasksLastCompletedFetchTimestamp ?? null}
    visibleTasks={state.settings.visibleTasks}
    changeVisibleTasks={(visibleTasks: VisibleTaskSettings) => updateSettings({ visibleTasks })}
    taskSort={state.settings.taskSortType}
    changeTaskSort={(taskSortType: TaskSortType) => updateSettings({ taskSortType })}
    badgeDisplay={state.settings.badgeDisplayType}
    changeBadgeDisplay={(badgeDisplayType: BadgeDisplayType) =>
      updateSettings({ badgeDisplayType })}
    showInactiveTasks={state.settings.showInactiveTasks}
    changeShowInactiveTasks={(showInactiveTasks: boolean) => updateSettings({ showInactiveTasks })}
    {client}
  />
{/if}

// src/popup/PopupWrapper.tsx
import { useMemoDeep } from "../common/hooks/useMemoDeep";
import type {
  Settings,
  VisibleTaskSettings,
  TaskSortType,
  CachedTasks,
  PersistentState,
  BadgeDisplayType,
} from "../common/state";
import { Popup } from "./Popup";
import { getClient } from "./popupClient";

interface Props {
  state: PersistentState;
  cachedTasks: CachedTasks;
  updateSettings: (settings: Settings) => void;
}

export function PopupWrapper(props: Props) {
  const connection = props.state.settings.connection;
  const client = useMemoDeep(() => getClient(connection), [connection]);

  return (
    <Popup
      tasks={props.cachedTasks.tasks}
      taskFetchFailureReason={props.cachedTasks.taskFetchFailureReason}
      tasksLastInitiatedFetchTimestamp={props.cachedTasks.tasksLastInitiatedFetchTimestamp}
      tasksLastCompletedFetchTimestamp={props.cachedTasks.tasksLastCompletedFetchTimestamp}
      visibleTasks={props.state.settings.visibleTasks}
      changeVisibleTasks={(visibleTasks: VisibleTaskSettings) => {
        props.updateSettings({ ...props.state.settings, visibleTasks });
      }}
      taskSort={props.state.settings.taskSortType}
      changeTaskSort={(taskSortType: TaskSortType) => {
        props.updateSettings({ ...props.state.settings, taskSortType });
      }}
      badgeDisplay={props.state.settings.badgeDisplayType}
      changeBadgeDisplay={(badgeDisplayType: BadgeDisplayType) => {
        props.updateSettings({ ...props.state.settings, badgeDisplayType });
      }}
      showInactiveTasks={props.state.settings.showInactiveTasks}
      changeShowInactiveTasks={(showInactiveTasks: boolean) => {
        props.updateSettings({ ...props.state.settings, showInactiveTasks });
      }}
      client={client}
    />
  );
}
