// src/popup/Popup.tsx
import "./popup.scss";
import * as React from "react";
import classNames from "classnames";
import throttle from "lodash-es/throttle";

import type { DownloadStationTask } from "../common/apis/synology/DownloadStation/Task";
import type { VisibleTaskSettings, TaskSortType, BadgeDisplayType } from "../common/state";
import { sortTasks, filterTasks } from "../common/filtering";
import { TaskFilterSettingsForm } from "../common/components/TaskFilterSettingsForm";
import { NonIdealState } from "../common/components/NonIdealState";
import type { PopupClient } from "./popupClient";
import { AdvancedAddDownloadForm } from "./AdvancedAddDownloadForm";
import { Header } from "./Header";
import { Footer } from "./Footer";
import { Task } from "./Task";

export interface Props {
  tasks: DownloadStationTask[];
  taskFetchFailureReason: "missing-config" | { failureMessage: string } | undefined;
  tasksLastInitiatedFetchTimestamp: number | undefined;
  tasksLastCompletedFetchTimestamp: number | undefined;
  visibleTasks: VisibleTaskSettings;
  changeVisibleTasks: (visibleTasks: VisibleTaskSettings) => void;
  taskSort: TaskSortType;
  changeTaskSort: (sort: TaskSortType) => void;
  badgeDisplay: BadgeDisplayType;
  changeBadgeDisplay: (display: BadgeDisplayType) => void;
  client: PopupClient;
}

interface State {
  isShowingDropShadow: boolean;
  isAddingDownload: boolean;
  isShowingDisplaySettings: boolean;
  isClearingCompletedTasks: boolean;
  // Bleh. If a popup grows larger in Firefox, it will leave it as such until the DOM changes and causes
  // a relayout. Therefore, after collapsing the filter panel, we want to force a layout to make it the right
  // size again. Unfortunately we can't do that by just reading a layout property like offsetHeight, we have
  // to actually change the DOM, hence we render this invisible nonce whenever we toggle the panel.
  firefoxRerenderNonce: number;
}

export class Popup extends React.PureComponent<Props, State> {
  private bodyRef?: HTMLElement;

  state: State = {
    isShowingDropShadow: false,
    isAddingDownload: false,
    isShowingDisplaySettings: false,
    isClearingCompletedTasks: false,
    firefoxRerenderNonce: 0,
  };

  render() {
    const completedTaskIds = this.props.tasks
      .filter((t) => t.status === "finished")
      .map((t) => t.id);
    const onClickClearTasks = this.props.client
      ? async () => {
          this.setState({ isClearingCompletedTasks: true });
          await this.props.client!.deleteTasks(completedTaskIds);
          this.setState({ isClearingCompletedTasks: false });
        }
      : undefined;

    return (
      <div className="popup">
        <Header
          isAddingDownload={this.state.isAddingDownload}
          onClickAddDownload={
            this.props.client != null
              ? () => {
                  this.setState({
                    isAddingDownload: !this.state.isAddingDownload,
                    isShowingDisplaySettings: false,
                  });
                }
              : undefined
          }
          completedTaskCount={completedTaskIds.length}
          onClickClearTasks={this.state.isClearingCompletedTasks ? "pending" : onClickClearTasks}
          onClickOpenDownloadStationUi={this.props.client?.openDownloadStationUi}
          isShowingDisplaySettings={this.state.isShowingDisplaySettings}
          onClickDisplaySettings={() => {
            this.setState({
              isShowingDisplaySettings: !this.state.isShowingDisplaySettings,
              isAddingDownload: false,
            });
          }}
          isMissingConfig={this.props.taskFetchFailureReason === "missing-config"}
          showDropShadow={this.state.isShowingDropShadow}
          disabledLogo={this.props.taskFetchFailureReason != null}
        />
        <div
          className={classNames("display-settings", {
            "is-visible": this.state.isShowingDisplaySettings,
          })}
        >
          <h4 className="title">{browser.i18n.getMessage("Task_Display_Settings")}</h4>
          <TaskFilterSettingsForm
            visibleTasks={this.props.visibleTasks}
            taskSortType={this.props.taskSort}
            badgeDisplayType={this.props.badgeDisplay}
            updateTaskTypeVisibility={this.updateTaskTypeVisibility}
            updateTaskSortType={this.props.changeTaskSort}
            updateBadgeDisplayType={this.props.changeBadgeDisplay}
          />
        </div>
        <div
          className={classNames("popup-body", { "with-foreground": this.state.isAddingDownload })}
          onScroll={this.onBodyScroll}
          ref={(e) => {
            this.bodyRef = e ?? undefined;
          }}
        >
          {this.renderTaskList()}
          {this.maybeRenderAddDownloadOverlay()}
        </div>
        <Footer
          tasks={this.props.tasks}
          taskFetchFailureReason={this.props.taskFetchFailureReason}
          tasksLastInitiatedFetchTimestamp={this.props.tasksLastInitiatedFetchTimestamp}
          tasksLastCompletedFetchTimestamp={this.props.tasksLastCompletedFetchTimestamp}
        />
        <div style={{ display: "none" }}>{this.state.firefoxRerenderNonce}</div>
      </div>
    );
  }

  private updateTaskTypeVisibility = (taskType: keyof VisibleTaskSettings, visibility: boolean) => {
    this.props.changeVisibleTasks({
      ...this.props.visibleTasks,
      [taskType]: visibility,
    });
  };

  private renderTaskList() {
    if (this.props.taskFetchFailureReason === "missing-config") {
      return (
        <NonIdealState
          icon="fa-cog"
          text={browser.i18n.getMessage(
            "Configure_your_hostname_username_and_password_in_settings",
          )}
        />
      );
    } else if (this.props.tasksLastCompletedFetchTimestamp == null) {
      return <NonIdealState icon="fa-sync fa-spin" />;
    } else if (this.props.tasks.length === 0) {
      return <NonIdealState text={browser.i18n.getMessage("No_download_tasks")} />;
    } else {
      const filteredTasks = filterTasks(this.props.tasks, this.props.visibleTasks);
      if (filteredTasks.length === 0) {
        return (
          <NonIdealState
            icon="fa-filter"
            text={browser.i18n.getMessage("Download_tasks_exist_but_none_match_your_filters")}
          />
        );
      } else {
        const hiddenTaskCount = this.props.tasks.length - filteredTasks.length;
        const deleteTask = this.props.client
          ? (taskId: string) => this.props.client!.deleteTasks([taskId])
          : undefined;
        return (
          <div className="download-tasks">
            <ul>
              {sortTasks(filteredTasks, this.props.taskSort).map((task) => (
                <Task
                  key={task.id}
                  task={task}
                  onDelete={deleteTask}
                  onPause={this.props.client?.pauseTask}
                  onResume={this.props.client?.resumeTask}
                />
              ))}
            </ul>
            {hiddenTaskCount > 0 && (
              <div
                className="hidden-count"
                onClick={() => {
                  this.setState({ isShowingDisplaySettings: true });
                }}
              >
                {browser.i18n.getMessage("and_ZcountZ_more_tasks_hidden_by_filters", [
                  hiddenTaskCount,
                ])}
              </div>
            )}
          </div>
        );
      }
    }
  }

  private maybeRenderAddDownloadOverlay() {
    if (this.state.isAddingDownload && this.props.client) {
      return (
        <div className="add-download-overlay">
          <div className="backdrop" />
          <div className="overlay-content">
            <AdvancedAddDownloadForm
              onClose={() => {
                this.setState({ isAddingDownload: false });
              }}
              client={this.props.client}
            />
          </div>
        </div>
      );
    } else {
      return null;
    }
  }

  private onBodyScroll = throttle(() => {
    if (this.bodyRef) {
      this.setState({ isShowingDropShadow: this.bodyRef.scrollTop !== 0 });
    } else {
      this.setState({ isShowingDropShadow: false });
    }
  }, 200);

  componentDidUpdate(_prevProps: Props, prevState: State) {
    if (prevState.isShowingDisplaySettings !== this.state.isShowingDisplaySettings) {
      setTimeout(() => {
        this.setState({ firefoxRerenderNonce: this.state.firefoxRerenderNonce + 1 });
      }, 350);
    }
  }
}

// src/popup/Popup.svelte
<script lang="ts">
  import Icon from "../common/components/Icon.svelte";
  import type { DownloadStationTask } from "../common/apis/synology/DownloadStation/Task";
  import type {
    VisibleTaskSettings,
    TaskSortType,
    BadgeDisplayType,
  } from "../common/state/defaults";
  import { sortTasks, filterTasks } from "../common/filtering";
  import TaskFilterSettingsForm from "../common/components/TaskFilterSettingsForm.svelte";
  import NonIdealState from "../common/components/NonIdealState.svelte";
  import type { PopupClient } from "./popupClient";
  import AdvancedAddDownloadForm from "./AdvancedAddDownloadForm.svelte";
  import Header from "./Header.svelte";
  import Footer from "./Footer.svelte";
  import Task from "./Task.svelte";
  import PasswordForm from "./PasswordForm.svelte";

  interface Props {
    tasks: DownloadStationTask[];
    taskFetchFailureReason: "missing-config" | "login-required" | { failureMessage: string } | null;
    tasksLastInitiatedFetchTimestamp: number | null;
    tasksLastCompletedFetchTimestamp: number | null;
    visibleTasks: VisibleTaskSettings;
    changeVisibleTasks: (visibleTasks: VisibleTaskSettings) => void;
    taskSort: TaskSortType;
    changeTaskSort: (sort: TaskSortType) => void;
    badgeDisplay: BadgeDisplayType;
    changeBadgeDisplay: (display: BadgeDisplayType) => void;
    showInactiveTasks: boolean;
    changeShowInactiveTasks: (show: boolean) => void;
    client?: PopupClient;
  }

  let {
    tasks,
    taskFetchFailureReason,
    tasksLastInitiatedFetchTimestamp,
    tasksLastCompletedFetchTimestamp,
    visibleTasks,
    changeVisibleTasks,
    taskSort,
    changeTaskSort,
    badgeDisplay,
    changeBadgeDisplay,
    showInactiveTasks,
    changeShowInactiveTasks,
    client,
  }: Props = $props();

  let isShowingDropShadow = $state(false);
  let isAddingDownload = $state(false);
  let isShowingDisplaySettings = $state(false);
  let isClearingCompletedTasks = $state(false);
  let bodyRef: HTMLElement | undefined;
  let scrollTimer: ReturnType<typeof setTimeout> | undefined;

  let completedTaskIds = $derived(tasks.filter((t) => t.status === "finished").map((t) => t.id));

  let onClickClearTasks = $derived.by(() => {
    if (!client) return undefined;
    return async () => {
      isClearingCompletedTasks = true;
      await client!.deleteTasks(completedTaskIds);
      isClearingCompletedTasks = false;
    };
  });

  let canAddDownload = $derived(client != null && taskFetchFailureReason !== "login-required");

  let filteredTasks = $derived(filterTasks(tasks, visibleTasks, showInactiveTasks));
  let sortedTasks = $derived(sortTasks(filteredTasks, taskSort));
  let hiddenTaskCount = $derived(tasks.length - filteredTasks.length);

  function updateTaskTypeVisibility(taskType: keyof VisibleTaskSettings, visibility: boolean) {
    changeVisibleTasks({ ...visibleTasks, [taskType]: visibility });
  }

  function onBodyScroll() {
    if (scrollTimer != null) return;
    scrollTimer = setTimeout(() => {
      scrollTimer = undefined;
      isShowingDropShadow = bodyRef ? bodyRef.scrollTop !== 0 : false;
    }, 200);
  }

  // Cleanup scroll timer on destroy
  $effect(() => {
    return () => {
      clearTimeout(scrollTimer);
    };
  });

  function deleteTask(taskId: string) {
    return client!.deleteTasks([taskId]);
  }
</script>

<div class="popup">
  <Header
    {isAddingDownload}
    onClickAddDownload={canAddDownload
      ? () => {
          isAddingDownload = !isAddingDownload;
          isShowingDisplaySettings = false;
        }
      : undefined}
    completedTaskCount={completedTaskIds.length}
    onClickClearTasks={isClearingCompletedTasks ? "pending" : onClickClearTasks}
    onClickOpenDownloadStationUi={client?.openDownloadStationUi}
    {isShowingDisplaySettings}
    onClickDisplaySettings={() => {
      isShowingDisplaySettings = !isShowingDisplaySettings;
      isAddingDownload = false;
    }}
    isMissingConfig={taskFetchFailureReason === "missing-config"}
    showDropShadow={isShowingDropShadow}
    disabledLogo={taskFetchFailureReason != null}
  />
  <div class="display-settings" class:is-visible={isShowingDisplaySettings}>
    <h4 class="title">{browser.i18n.getMessage("Task_Display_Settings")}</h4>
    <TaskFilterSettingsForm
      {visibleTasks}
      taskSortType={taskSort}
      badgeDisplayType={badgeDisplay}
      {showInactiveTasks}
      {updateTaskTypeVisibility}
      updateTaskSortType={changeTaskSort}
      updateBadgeDisplayType={changeBadgeDisplay}
      updateShowInactiveTasks={changeShowInactiveTasks}
    />
  </div>
  <div
    class="popup-body"
    class:with-foreground={isAddingDownload}
    onscroll={onBodyScroll}
    bind:this={bodyRef}
  >
    <!-- Task list -->
    {#if taskFetchFailureReason === "missing-config"}
      <NonIdealState
        text={browser.i18n.getMessage("Configure_your_hostname_username_and_password_in_settings")}
      >
        {#snippet icon()}<Icon name="gear" size="2x" />{/snippet}
      </NonIdealState>
    {:else if taskFetchFailureReason === "login-required"}
      {#if !client}
        <NonIdealState />
      {:else}
        <NonIdealState text={browser.i18n.getMessage("Password_required")}>
          {#snippet icon()}<Icon name="lock" size="2x" />{/snippet}
          <PasswordForm {client} />
        </NonIdealState>
      {/if}
    {:else if tasksLastCompletedFetchTimestamp == null}
      <NonIdealState>
        {#snippet icon()}<Icon name="arrows-rotate" size="2x" spin />{/snippet}
      </NonIdealState>
    {:else if tasks.length === 0}
      <NonIdealState text={browser.i18n.getMessage("No_download_tasks")} />
    {:else if filteredTasks.length === 0}
      <NonIdealState
        text={browser.i18n.getMessage("Download_tasks_exist_but_none_match_your_filters")}
      >
        {#snippet icon()}<Icon name="filter" size="2x" />{/snippet}
      </NonIdealState>
    {:else}
      <div class="download-tasks">
        <ul>
          {#each sortedTasks as task (task.id)}
            <Task
              {task}
              onDelete={client ? deleteTask : undefined}
              onPause={client?.pauseTask}
              onResume={client?.resumeTask}
            />
          {/each}
        </ul>
        {#if hiddenTaskCount > 0}
          <div
            class="hidden-count"
            onclick={() => {
              isShowingDisplaySettings = true;
            }}
            role="button"
            tabindex="0"
            onkeydown={(e) => {
              if (e.key === "Enter") isShowingDisplaySettings = true;
            }}
          >
            {browser.i18n.getMessage("and_ZcountZ_more_tasks_hidden_by_filters", [hiddenTaskCount])}
          </div>
        {/if}
      </div>
    {/if}

    <!-- Add download overlay -->
    {#if isAddingDownload && client}
      <div class="add-download-overlay">
        <div class="backdrop"></div>
        <div class="overlay-content">
          <AdvancedAddDownloadForm
            onClose={() => {
              isAddingDownload = false;
            }}
            {client}
          />
        </div>
      </div>
    {/if}
  </div>
  <Footer
    {tasks}
    {taskFetchFailureReason}
    {tasksLastInitiatedFetchTimestamp}
    {tasksLastCompletedFetchTimestamp}
  />
</div>

<style>
  .popup {
    display: flex;
    flex-direction: column;

    .display-settings {
      flex-shrink: 0;
      max-height: 0px;
      /* If Firefox fails to reflow after this transition, try:
         1. interpolate-size: allow-keywords on the container
         2. bind:clientHeight with explicit height instead of max-height
         3. As last resort, a nonce-based forced rerender via $effect */
      transition: max-height 300ms;
      overflow: hidden;

      &.is-visible {
        max-height: 1000px;
        border-bottom: 1px solid rgba(0, 0, 0, 0.2);
      }

      h4 {
        margin-left: 15px;
      }

      :global(.task-filter-settings-form select) {
        margin-right: 15px;
      }
    }

    .popup-body {
      flex: 1;
      overflow-y: auto;
      position: relative;
      min-height: 50px;

      &.with-foreground {
        min-height: 400px;

        > :not(.add-download-overlay) {
          filter: blur(3px);
        }

        .download-tasks {
          overflow-y: hidden;
          height: 100%;
        }
      }
    }
  }

  .download-tasks {
    .hidden-count {
      flex: 1;
      display: flex;
      justify-content: center;
      align-items: center;
      margin-top: 5px;
      margin-bottom: 10px;

      &:hover {
        text-decoration: underline;
        cursor: pointer;
      }
    }

    ul {
      list-style: none;
      margin: 0;
      padding: 0;
    }
  }

  .popup-body .add-download-overlay {
    position: absolute;
    top: 0;
    bottom: 0;
    left: 0;
    right: 0;

    .backdrop {
      width: 100%;
      height: 100%;
      background-color: rgba(0, 0, 0, 0.2);
      filter: blur(0.5px);
    }

    .overlay-content {
      position: absolute;
      top: 0;
      left: 0;
      right: 0;
      bottom: 0;
      padding: 10px;
    }

    :global(.advanced-add-download-form) {
      height: 100%;

      :global(.download-path) {
        flex: 1;
      }
    }
  }
</style>
