// src/common/components/SettingsListCheckbox.svelte
<script lang="ts">
  interface Props {
    checked: boolean;
    onChange: () => void;
    label: string;
    title?: string;
  }

  let { checked, onChange, label, title }: Props = $props();

  const uid = $props.id();
</script>

<li {title}>
  <input id="{uid}-checkbox" type="checkbox" {checked} onchange={onChange} />
  <label for="{uid}-checkbox">{label}</label>
</li>

// src/common/components/SettingsListCheckbox.tsx
import { useId } from "react";

export interface Props {
  checked: boolean;
  onChange: () => void;
  label: string;
  title?: string;
}

export function SettingsListCheckbox(props: Props) {
  const id = useId();
  return (
    <li title={props.title}>
      <input id={id} type="checkbox" checked={props.checked} onChange={props.onChange} />
      <label htmlFor={id}>{props.label}</label>
    </li>
  );
}
