// src/settings/ConnectionSettings.svelte
<script lang="ts">
  import type { ConnectionSettings as ConnectionSettingsObject } from "../common/state/defaults";
  import { TestConnection } from "../common/apis/messages";
  import SettingsList from "../common/components/SettingsList.svelte";
  import LoginStatus from "../common/components/LoginStatus.svelte";
  import type { Status } from "../common/components/LoginStatus.svelte";
  import type { Overwrite } from "../common/types";
  import { assert } from "../common/lang";

  type ConnectionSettingsWithMandatoryPassword = Overwrite<
    ConnectionSettingsObject,
    { password: string }
  >;

  interface Props {
    connectionSettings: ConnectionSettingsObject;
    saveConnectionSettings: (settings: ConnectionSettingsWithMandatoryPassword) => void;
  }

  let { connectionSettings, saveConnectionSettings }: Props = $props();

  let changedSettings = $state<Partial<ConnectionSettingsWithMandatoryPassword>>({});
  let loginStatus = $state<Status>("none");

  const uid = $props.id();

  let mergedSettings = $derived({ ...connectionSettings, ...changedSettings });
  let canEditFields = $derived(loginStatus !== "in-progress");

  function setSetting<K extends keyof ConnectionSettingsWithMandatoryPassword>(
    key: K,
    value: ConnectionSettingsWithMandatoryPassword[K],
  ) {
    loginStatus = "none";
    changedSettings = { ...changedSettings, [key]: value };
  }

  async function testConnectionAndSave(settings: ConnectionSettingsWithMandatoryPassword) {
    // Firefox MV3 treats host_permissions as optional. Ensure they're granted
    // before attempting to connect to the NAS.
    const hasPermission = await browser.permissions.contains({ origins: ["<all_urls>"] });
    if (!hasPermission) {
      const granted = await browser.permissions.request({ origins: ["<all_urls>"] });
      if (!granted) {
        loginStatus = {
          type: "unknown",
          error: "Host permission is required to connect to your NAS",
        };
        return;
      }
    }
    loginStatus = "in-progress";
    const result = await TestConnection.send(
      settings.hostname,
      settings.port,
      settings.username,
      settings.password,
    );
    if (result.success) {
      loginStatus = {
        success: true,
        data: {},
        meta: { apiGroup: "Auth", method: "login", version: 6 },
      };
      saveConnectionSettings(settings);
    } else {
      loginStatus = { type: "unknown", error: result.reason };
    }
  }

  let submitDisabled = $derived(
    !canEditFields ||
      !mergedSettings.hostname ||
      !mergedSettings.port ||
      !mergedSettings.username ||
      !mergedSettings.password ||
      loginStatus === "in-progress",
  );
</script>

<form
  onsubmit={(e) => {
    e.preventDefault();
    assert(mergedSettings.password != null);
    testConnectionAndSave(mergedSettings as ConnectionSettingsWithMandatoryPassword);
  }}
  class="connection-settings"
>
  <SettingsList>
    <li class="label-and-input host-settings">
      <span class="label">{browser.i18n.getMessage("Host")}</span>
      <div class="input">
        <span>https://</span>
        <input
          type="text"
          disabled={!canEditFields}
          class="host-setting"
          placeholder={browser.i18n.getMessage("hostname_or_IP_address")}
          value={mergedSettings.hostname}
          oninput={(e) => setSetting("hostname", e.currentTarget.value.trim())}
        />
        <span>:</span>
        <input
          disabled={!canEditFields}
          class="port-setting"
          type="number"
          value={mergedSettings.port === 0 ? "" : mergedSettings.port}
          oninput={(e) => {
            const port = +(e.currentTarget.value.replace(/[^0-9]/g, "") || 0);
            setSetting("port", port);
          }}
        />
      </div>
    </li>

    <li class="label-and-input">
      <span class="label">{browser.i18n.getMessage("Username")}</span>
      <div class="input">
        <input
          type="text"
          disabled={!canEditFields}
          value={mergedSettings.username}
          oninput={(e) => setSetting("username", e.currentTarget.value)}
        />
      </div>
    </li>

    <li class="label-and-input">
      <span class="label">{browser.i18n.getMessage("Password")}</span>
      <div class="input">
        <input
          type="password"
          disabled={!canEditFields}
          value={mergedSettings.password ?? ""}
          oninput={(e) => setSetting("password", e.currentTarget.value)}
        />
      </div>
    </li>

    <li class="label-and-input remember-me">
      <input
        type="checkbox"
        disabled={!canEditFields}
        class:disabled={!canEditFields}
        id="{uid}-remember"
        checked={mergedSettings.rememberPassword}
        onchange={() => setSetting("rememberPassword", !mergedSettings.rememberPassword)}
      />
      <label for="{uid}-remember">{browser.i18n.getMessage("Remember_Password")}</label>
    </li>

    <li>
      <LoginStatus status={loginStatus} />
      <button type="submit" disabled={submitDisabled}>
        {browser.i18n.getMessage("Login")}
      </button>
    </li>
  </SettingsList>
</form>

<style>
  .connection-settings {
    .remember-me input {
      margin-left: auto;
    }
  }
</style>

// src/settings/ConnectionSettings.tsx
import "./connection-settings.css";

import { useId, useState } from "react";

import {
  Protocol,
  PROTOCOLS,
  ConnectionSettings as ConnectionSettingsObject,
} from "../common/state";
import { ClientRequestResult } from "../common/apis/synology";
import { SettingsList } from "../common/components/SettingsList";
import { disabledPropAndClassName, kludgeRefSetClassname } from "../common/classnameUtil";
import type { Overwrite } from "../common/types";
import { assert } from "../common/lang";
import { testConnection } from "../common/apis/connection";
import { LoginStatus, Status } from "../common/components/LoginStatus";

type ConnectionSettingsWithMandatoryPassword = Overwrite<
  ConnectionSettingsObject,
  { password: string }
>;

interface Props {
  connectionSettings: ConnectionSettingsObject;
  saveConnectionSettings: (settings: ConnectionSettingsWithMandatoryPassword) => void;
}

export function ConnectionSettings(props: Props) {
  const [changedSettings, setChangedSettings] = useState<
    Partial<ConnectionSettingsWithMandatoryPassword>
  >({});
  const [loginStatus, setLoginStatus] = useState<Status>("none");
  const checkboxId = useId();

  const canEditFields = loginStatus !== "in-progress";
  const mergedSettings = { ...props.connectionSettings, ...changedSettings };

  function setSetting<K extends keyof ConnectionSettingsWithMandatoryPassword>(
    key: K,
    value: ConnectionSettingsWithMandatoryPassword[K],
  ) {
    setLoginStatus("none");
    setChangedSettings((settings) => ({ ...settings, [key]: value }));
  }

  async function testConnectionAndSave(settings: ConnectionSettingsWithMandatoryPassword) {
    setLoginStatus("in-progress");

    const result = await testConnection(settings);

    setLoginStatus(result);

    if (!ClientRequestResult.isConnectionFailure(result) && result.success) {
      props.saveConnectionSettings(settings);
    }
  }

  return (
    <form
      onSubmit={(e) => {
        e.preventDefault();
        assert(mergedSettings.password != null);
        testConnectionAndSave(mergedSettings as ConnectionSettingsWithMandatoryPassword);
      }}
      className="connection-settings"
    >
      <SettingsList>
        <li className="label-and-input host-settings">
          <span className="label">{browser.i18n.getMessage("Host")}</span>
          <div className="input">
            <select
              {...disabledPropAndClassName(!canEditFields)}
              value={mergedSettings.protocol}
              onChange={(e) => {
                setSetting("protocol", e.currentTarget.value as Protocol);
              }}
              ref={kludgeRefSetClassname("protocol-setting")}
            >
              {PROTOCOLS.map((protocol) => (
                <option key={protocol} value={protocol}>
                  {protocol}
                </option>
              ))}
            </select>
            <span>://</span>
            <input
              type="text"
              {...disabledPropAndClassName(!canEditFields)}
              placeholder={browser.i18n.getMessage("hostname_or_IP_address")}
              value={mergedSettings.hostname}
              onChange={(e) => {
                setSetting("hostname", e.currentTarget.value.trim());
              }}
              ref={kludgeRefSetClassname("host-setting")}
            />
            <span>:</span>
            <input
              {...disabledPropAndClassName(!canEditFields)}
              type="number"
              value={mergedSettings.port === 0 ? "" : mergedSettings.port}
              onChange={(e) => {
                const port = +(e.currentTarget.value.replace(/[^0-9]/g, "") || 0);
                setSetting("port", port);
              }}
              ref={kludgeRefSetClassname("port-setting")}
            />
          </div>
        </li>

        <li className="label-and-input">
          <span className="label">{browser.i18n.getMessage("Username")}</span>
          <div className="input">
            <input
              type="text"
              {...disabledPropAndClassName(!canEditFields)}
              value={mergedSettings.username}
              onChange={(e) => {
                setSetting("username", e.currentTarget.value);
              }}
            />
          </div>
        </li>

        <li className="label-and-input">
          <span className="label">{browser.i18n.getMessage("Password")}</span>
          <div className="input">
            <input
              type="password"
              {...disabledPropAndClassName(!canEditFields)}
              value={mergedSettings.password ?? ""}
              onChange={(e) => {
                setSetting("password", e.currentTarget.value);
              }}
            />
          </div>
        </li>

        <li className="label-and-input remember-me">
          <input
            type="checkbox"
            {...disabledPropAndClassName(!canEditFields)}
            id={checkboxId}
            checked={mergedSettings.rememberPassword}
            onChange={() => {
              setSetting("rememberPassword", !mergedSettings.rememberPassword);
            }}
          />
          <label htmlFor={checkboxId}>{browser.i18n.getMessage("Remember_Password")}</label>
        </li>

        <li>
          <LoginStatus status={loginStatus} />
          <button
            type="submit"
            {...disabledPropAndClassName(
              !canEditFields ||
                !mergedSettings.protocol ||
                !mergedSettings.hostname ||
                !mergedSettings.port ||
                !mergedSettings.username ||
                !mergedSettings.password ||
                (loginStatus !== "none" &&
                  !ClientRequestResult.isConnectionFailure(loginStatus) &&
                  loginStatus.success),
            )}
          >
            {browser.i18n.getMessage("Login")}
          </button>
        </li>
      </SettingsList>
    </form>
  );
}
