// src/popup/PathSelector.svelte
<script lang="ts">
  import Icon from "../common/components/Icon.svelte";
  import type { MessageResponse, Directory } from "../common/apis/messages";
  import DirectoryTree from "./DirectoryTree.svelte";
  import {
    type DirectoryTreeFile,
    isUnloadedChild,
    isLoadedChild,
    isErrorChild,
    recursivelyUpdateDirectoryTree,
  } from "./directoryTreeHelpers";
  import type { PopupClient } from "./popupClient";

  const ROOT_PATH = "/";

  interface Props {
    selectedPath: string | undefined;
    onSelectPath: (path: string | undefined) => void;
    client: PopupClient;
  }

  let { selectedPath, onSelectPath, client }: Props = $props();

  let directoryTree = $state<DirectoryTreeFile>({
    name: "/",
    path: ROOT_PATH,
    children: "unloaded",
  });

  const requestVersionByPath: Record<string, number> = {};

  function updateTreeWithResponse(path: string, response: MessageResponse<Directory[]>) {
    if (response.success) {
      directoryTree = recursivelyUpdateDirectoryTree(
        directoryTree,
        path,
        response.result.map((c) => ({ ...c, children: "unloaded" as const })),
      );
    } else {
      directoryTree = recursivelyUpdateDirectoryTree(directoryTree, path, {
        failureMessage: response.reason,
      });
    }
  }

  async function loadTopLevelDirectories() {
    directoryTree = recursivelyUpdateDirectoryTree(directoryTree, ROOT_PATH, "unloaded");
    const stashedRequestVersion = (requestVersionByPath[ROOT_PATH] =
      (requestVersionByPath[ROOT_PATH] || 0) + 1);
    const response = await client.listDirectories();
    if (stashedRequestVersion === requestVersionByPath[ROOT_PATH]) {
      updateTreeWithResponse(ROOT_PATH, response);
    }
  }

  async function loadNestedDirectory(path: string) {
    if (!isLoadedChild(directoryTree.children)) {
      console.error(
        `programmer error: cannot load nested directories when top-level directories are not in a valid state`,
      );
      return;
    }
    const stashedRequestVersion = (requestVersionByPath[path] =
      (requestVersionByPath[path] || 0) + 1);
    const response = await client.listDirectories(path);
    if (stashedRequestVersion === requestVersionByPath[path]) {
      updateTreeWithResponse(path, response);
    }
  }

  // Load directories on mount (component is recreated each time the form opens)
  loadTopLevelDirectories();
</script>

<div class="path-selector">
  {#if isUnloadedChild(directoryTree.children)}
    <div class="no-content">{browser.i18n.getMessage("Loading_directories")}</div>
  {:else if isErrorChild(directoryTree.children)}
    <div class="no-content intent-error">
      <Icon name="triangle-exclamation" />
      {directoryTree.children.failureMessage}
    </div>
  {:else if directoryTree.children.length === 0}
    <div class="no-content">{browser.i18n.getMessage("No_directories")}</div>
  {:else}
    <div>
      {#each directoryTree.children as directory (directory.path)}
        <DirectoryTree
          file={directory}
          requestLoad={loadNestedDirectory}
          {selectedPath}
          onSelect={onSelectPath}
        />
      {/each}
    </div>
  {/if}
</div>

<style>
  .path-selector {
    .no-content {
      padding: 5px;
      display: flex;
      align-items: center;
      justify-content: center;

      &:not(.intent-error) {
        color: #999;
      }
    }
  }
</style>

// src/common/PathSelector.tsx
import * as React from 'react';
import { ApiClient, SynologyResponse, ConnectionFailure, isConnectionFailure } from 'synology-typescript-api';
import { errorMessageFromConnectionFailure, errorMessageFromCode } from '../apiErrors';
import {
  DirectoryTree,
  DirectoryTreeFile,
  isUnloadedChild,
  isLoadedChild,
  isErrorChild,
  recursivelyUpdateDirectoryTree
} from './DirectoryTree';

const ROOT_PATH = '/';

export interface Props {
  client: ApiClient;
  selectedPath: string | undefined;
  onSelectPath: (path: string | undefined) => void;
}

export interface State {
  directoryTree: DirectoryTreeFile;
}

export class PathSelector extends React.PureComponent<Props, State> {
  state: State = {
    directoryTree: {
      name: '/',
      path: ROOT_PATH,
      children: 'unloaded'
    }
  };

  private unsubscribeCallback: (() => void) | undefined;
  private requestVersionByPath: Record<string, number> = {};

  render() {
    return (
      <div className='path-selector'>
        {this.renderContent()}
      </div>
    );
  }

  private renderContent() {
    if (isUnloadedChild(this.state.directoryTree.children)) {
      return (
        <div className='no-content'>Loading directories...</div>
      );
    } else if (isErrorChild(this.state.directoryTree.children)) {
      return (
        <div className='no-content intent-error'>
          <span className='fa fa-exclamation-triangle'/>
          {this.state.directoryTree.children.failureMessage}
        </div>
      );
    } else if (this.state.directoryTree.children.length === 0) {
      return <div className='no-content'>No directories.</div>;
    } else {
      return (
        <div>
          {this.state.directoryTree.children.map(directory => (
            <DirectoryTree
              key={directory.path}
              file={directory}
              requestLoad={this.loadNestedDirectory}
              selectedPath={this.props.selectedPath}
              onSelect={this.props.onSelectPath}
            />
          ))}
        </div>
      );
    }
  }

  private unsubscribeFromClient() {
    if (this.unsubscribeCallback) {
      this.unsubscribeCallback();
      this.unsubscribeCallback = undefined;
    }
  }

  private subscribeToClient(client: ApiClient) {
    this.unsubscribeFromClient();
    this.unsubscribeCallback = client.onSettingsChange(this.loadTopLevelDirectories);
  }

  componentDidMount() {
    this.subscribeToClient(this.props.client);
    this.loadTopLevelDirectories();
  }

  componentWillUnmount() {
    this.unsubscribeFromClient();
  }

  componentWillReceiveProps(nextProps: Props) {
    if (this.props.client !== nextProps.client) {
      this.unsubscribeFromClient();
      this.subscribeToClient(this.props.client);
      this.loadTopLevelDirectories();
    }
  }

  private loadNestedDirectory = (path: string) => {
    if (!isLoadedChild(this.state.directoryTree.children)) {
      console.error(`programmer error: cannot load nested directories when top-level directories are not in a valid state`);
    } else {
      const stashedRequestVersion = this.requestVersionByPath[path] = (this.requestVersionByPath[path] || 0) + 1;
      this.props.client.FileStation.List.list({ folder_path: path, sort_by: 'name', filetype: 'dir' })
        .then(response => {
          if (stashedRequestVersion === this.requestVersionByPath[path]) {
            this.updateTreeWithResponse(path, response, data => data.files.map(f => ({
              path: f.path,
              name: f.name,
              children: 'unloaded' as 'unloaded'
            })));
          }
        });
    }
  };

  private loadTopLevelDirectories = () => {
    this.setState({
      directoryTree: recursivelyUpdateDirectoryTree(this.state.directoryTree, ROOT_PATH, 'unloaded')
    });
    const stashedRequestVersion = this.requestVersionByPath[ROOT_PATH] = (this.requestVersionByPath[ROOT_PATH] || 0) + 1;
    this.props.client.FileStation.List.list_share({ sort_by: 'name' })
      .then(response => {
        if (stashedRequestVersion === this.requestVersionByPath[ROOT_PATH]) {
          this.updateTreeWithResponse(ROOT_PATH, response, data => data.shares.map(d => ({
            name: d.name,
            path: d.path,
            children: 'unloaded' as 'unloaded'
          })));
        }
      });
  };

  private updateTreeWithResponse<T>(path: string, response: SynologyResponse<T> | ConnectionFailure, parseChildren: (data: T) => DirectoryTreeFile[]) {
    if (isConnectionFailure(response)) {
      this.setState({
        directoryTree: recursivelyUpdateDirectoryTree(this.state.directoryTree, path, {
          failureMessage: errorMessageFromConnectionFailure(response)
        })
      });
    } else if (!response.success) {
      this.setState({
        directoryTree: recursivelyUpdateDirectoryTree(this.state.directoryTree, path, {
          failureMessage: errorMessageFromCode(response.error.code, 'FileStation')
        })
      });
    } else {
      this.setState({
        directoryTree: recursivelyUpdateDirectoryTree(this.state.directoryTree, path, parseChildren(response.data))
      });
    }
  }
}
